Last changes

diff --git a/scripts/es-bluetooth b/scripts/es-bluetooth
--- a/scripts/es-bluetooth
+++ b/scripts/es-bluetooth
@@ -762,11 +762,17 @@ do_auto_connect_audio_device_off()
 
 LOG_FILE="$ES_SCRIPT_LOGS_DIR/es-bluetooth.log"
 
-
 #if [ -f "$LOG_FILE" ]; then
 #  mv "$LOG_FILE" "$LOG_FILE.bak"
 #fi
 
+exit_execution()
+{
+    local return=$1
+    local param1=$2
+    #print_log $LOG_FILE "INFO" "##### Exit executing operation: '$ACTION $param1', exit code: '$return' #####"
+    exit $return
+}
 
 if [ $# -eq 0 ]; then
   do_help
@@ -776,44 +782,44 @@ fi
 ACTION=$1
 shift
 
-#print_log $LOG_FILE "INFO" "##### Executing operation: $ACTION #####"
+#print_log $LOG_FILE "INFO" "##### Executing operation: '$ACTION $1' #####"
 
 case "${ACTION}" in
     "scan_on")
-        do_scan_on || exit 1
+        do_scan_on || exit_execution 1
     ;;
     "scan_off")
-        do_scan_off || exit 1
+        do_scan_off || exit_execution 1
     ;;
     "new_devices")
-        get_new_devices_list || exit 1
+        get_new_devices_list || exit_execution 1
     ;;
     "enable")
-        do_enable || exit 1
+        do_enable || exit_execution 1
     ;;
     "disable")
-        do_disable || exit 1
+        do_disable || exit_execution 1
     ;;
     "enable_bluetooth")
-        enable_bluetooth || exit 1
+        enable_bluetooth || exit_execution 1
     ;;
     "disable_bluetooth")
-        disable_bluetooth || exit 1
+        disable_bluetooth || exit_execution 1
     ;;
     "toggle")
-        do_toggle_bluetooth || exit 1
+        do_toggle_bluetooth || exit_execution 1
     ;;
     "is_bluetooth_active")
-        is_bluetooth_active || exit 1
+        is_bluetooth_active || exit_execution 1
     ;;
     "is_bluetooth_enabled")
-        is_bluetooth_enabled || exit 1
+        is_bluetooth_enabled || exit_execution 1
     ;;
     "is_bluetooth_audio_device")
-        is_bluetooth_audio_device "$1" || exit 1
+        is_bluetooth_audio_device "$1" || exit_execution 1 "$1"
     ;;
     "is_bluetooth_audio_device_connected")
-        is_bluetooth_audio_device_connected || exit 1
+        is_bluetooth_audio_device_connected || exit_execution 1
     ;;
     "audio_device_connected")
         get_bluetooth_audio_device_connected
@@ -822,7 +828,7 @@ case "${ACTION}" in
         get_info_device "$1"
     ;;
     "pair_device")
-        do_pair_device "$1" || exit 1
+        do_pair_device "$1" || exit_execution 1 "$1"
     ;;
     "paired_devices")
         get_paired_devices
@@ -831,28 +837,28 @@ case "${ACTION}" in
         get_connected_devices
     ;;
     "disconnect_device")
-        do_disconnect_device "$1" || exit 1
+        do_disconnect_device "$1" || exit_execution 1 "$1"
     ;;
     "disconnect_all_devices")
-        do_disconnect_all_devices || exit 1
+        do_disconnect_all_devices || exit_execution 1
     ;;
     "connect_device")
-        do_connect_device "$1" || exit 1
+        do_connect_device "$1" || exit_execution 1 "$1"
     ;;
     "delete_device_connection")
-        do_delete_device_connection "$1" || exit 1
+        do_delete_device_connection "$1" || exit_execution 1 "$1"
     ;;
     "delete_all_device_connections")
-        do_delete_all_device_connections || exit 1
+        do_delete_all_device_connections || exit_execution 1
     ;;
     "auto_connect_audio_device_on")
-        do_auto_connect_audio_device_on || exit 1
+        do_auto_connect_audio_device_on || exit_execution 1
     ;;
     "auto_connect_audio_device_off")
-        do_auto_connect_audio_device_off || exit 1
+        do_auto_connect_audio_device_off || exit_execution 1
     ;;
     "test_bluetooth")
-        test_bluetooth || exit 1
+        test_bluetooth || exit_execution 1
     ;;
     *)
         do_help
@@ -861,5 +867,4 @@ case "${ACTION}" in
         exit 1
 esac
 
-#print_log $LOG_FILE "INFO" "##### Exit executing operation: $ACTION #####"
-exit 0
+exit_execution 0 "$1"
diff --git a/scripts/es-optimize_system b/scripts/es-optimize_system
--- a/scripts/es-optimize_system
+++ b/scripts/es-optimize_system
@@ -216,23 +216,27 @@ LOG_FILE="$ES_SCRIPT_LOGS_DIR/es-optimize_system.log"
 #  mv "$LOG_FILE" "$LOG_FILE.bak"
 #fi
 
-
 if [ $# -eq 0 ]; then
   do_help
   exit 1
 fi
 
+exit_execution()
+{
+    local return=$1
+    local param1=$2
+    #print_log $LOG_FILE "INFO" "##### Exit executing operation: '$ACTION $param1', exit code: '$return' #####"
+    exit $return
+}
 
 ACTION=$1
-VALUE=$2
-VALUE2=$3
 shift
 
-#print_log $LOG_FILE "INFO" "##### Executing operation: '$ACTION', value: $VALUE, value2: $VALUE2 #####"
+#print_log $LOG_FILE "INFO" "##### Executing operation: '$ACTION $1' #####"
 
 case "${ACTION}" in
     "active_optimize_system")
-        do_active_optimize_system "$VALUE"
+        do_active_optimize_system "$1"
         remove_log
         remove_journal
     ;;
@@ -243,5 +247,4 @@ case "${ACTION}" in
         exit 1
 esac
 
-#print_log $LOG_FILE "INFO" "##### Exit executing operation: $ACTION #####"
-exit 0
+exit_execution 0 "$1"
diff --git a/scripts/es-remote_services b/scripts/es-remote_services
--- a/scripts/es-remote_services
+++ b/scripts/es-remote_services
@@ -381,11 +381,19 @@ do_set_status()
 EXIST_CONNECTION_FLAG=" (**)"
 LOG_FILE="$ES_SCRIPT_LOGS_DIR/es-remote_services.log"
 
-
 #if [ -f "$LOG_FILE" ]; then
 #  mv "$LOG_FILE" "$LOG_FILE.bak"
 #fi
 
+exit_execution()
+{
+    local return=$1
+    local param1=$2
+    local param2=$3
+    local param3=$4
+    #print_log $LOG_FILE "INFO" "##### Exit executing operation: '$ACTION $param1 $param2 $param3', exit code: '$return' #####"
+    exit $return
+}
 
 if [ $# -eq 0 ]; then
   do_help
@@ -395,26 +403,26 @@ fi
 ACTION=$1
 shift
 
-#print_log $LOG_FILE "INFO" "##### Executing operation: $ACTION #####"
+#print_log $LOG_FILE "INFO" "##### Executing operation: '$ACTION $1 $2 $3' #####"
 
 case "${ACTION}" in
     "enable")
-        do_enable "$1" || exit 1
+        do_enable "$1" || exit_execution 1 "$1"
     ;;
     "disable")
-        do_disable "$1" || exit 1
+        do_disable "$1" || exit_execution 1 "$1"
     ;;
     "active")
-        do_active "$1" || exit 1
+        do_active "$1" || exit_execution 1 "$1"
     ;;
     "inactive")
-        do_inactive "$1" || exit 1
+        do_inactive "$1" || exit_execution 1 "$1"
     ;;
     "is_enabled")
-        is_enabled "$1" || exit 1
+        is_enabled "$1" || exit_execution 1 "$1"
     ;;
     "is_actived")
-        is_actived "$1" || exit 1
+        is_actived "$1" || exit_execution 1 "$1"
     ;;
     "get_status")
         do_get_status "$1"
@@ -423,7 +431,7 @@ case "${ACTION}" in
         do_get_status_detail "$1"
     ;;
     "set_status")
-        do_set_status "$1" "$2" "$3" || exit 1
+        do_set_status "$1" "$2" "$3" || exit_execution 1 "$1" "$2" "$3"
     ;;
     *)
         do_help
@@ -432,5 +440,4 @@ case "${ACTION}" in
         exit 1
 esac
 
-#print_log $LOG_FILE "INFO" "##### Exit executing operation: $ACTION #####"
-exit 0
+exit_execution 0 "$1" "$2" "$3"
diff --git a/scripts/es-wifi b/scripts/es-wifi
--- a/scripts/es-wifi
+++ b/scripts/es-wifi
@@ -425,11 +425,19 @@ set_wifi_power_safe()
 
 LOG_FILE="$ES_SCRIPT_LOGS_DIR/es-wifi.log"
 
-
 #if [ -f "$LOG_FILE" ]; then
 #  mv "$LOG_FILE" "$LOG_FILE.bak"
 #fi
 
+exit_execution()
+{
+    local return=$1
+    local param1=$2
+    local param2=$3
+    local param3=$4
+    #print_log $LOG_FILE "INFO" "##### Exit executing operation: '$ACTION $param1 $param2 $param3', exit code: '$return' #####"
+    exit $return
+}
 
 if [ $# -eq 0 ]; then
   do_help
@@ -439,7 +447,7 @@ fi
 ACTION=$1
 shift
 
-#print_log $LOG_FILE "INFO" "##### Executing operation: $ACTION #####"
+#print_log $LOG_FILE "INFO" "##### Executing operation: '$ACTION $1 $2 $3' #####"
 
 case "${ACTION}" in
     "list")
@@ -452,31 +460,31 @@ case "${ACTION}" in
         do_start
     ;;
     "connect")
-        do_connect "$1" "$2" || exit 1
+        do_connect "$1" "$2" || exit_execution 1 "$1" "$2"
     ;;
     "disconnect")
-        do_disconnect "$1" || exit 1
+        do_disconnect "$1" || exit_execution 1 "$1"
     ;;
     "remove")
-        do_remove "$1" || exit 1
+        do_remove "$1" || exit_execution 1 "$1"
     ;;
     "reset")
-        do_reset "$1" || exit 1
+        do_reset "$1" || exit_execution 1 "$1"
     ;;
     "enable")
-        do_enable || exit 1
+        do_enable || exit_execution 1
     ;;
     "disable")
-        do_disable || exit 1
+        do_disable || exit_execution 1
     ;;
     "internet_status")
-        do_test_internet || exit 1
+        do_test_internet || exit_execution 1
     ;;
     "is_connected")
-        is_connected || exit 1
+        is_connected || exit_execution 1
     ;;
     "is_enabled")
-        is_enabled || exit 1
+        is_enabled || exit_execution 1
     ;;
     "get_ssid")
         get_ssid
@@ -491,22 +499,22 @@ case "${ACTION}" in
         get_dns2
     ;;
     "enable_manual_dns")
-        enable_manual_dns "$1" "$2" "$3" || exit 1
+        enable_manual_dns "$1" "$2" "$3" || exit_execution 1 "$1" "$2" "$3"
     ;;
     "disable_manual_dns")
-        disable_manual_dns "$1" || exit 1
+        disable_manual_dns "$1" || exit_execution 1
     ;;
     "enable_network_manager")
-        enable_network_manager || exit 1
+        enable_network_manager || exit_execution 1
     ;;
     "disable_network_manager")
-        disable_network_manager || exit 1
+        disable_network_manager || exit_execution 1
     ;;
     "is_network_manager_active")
-        is_network_manager_active || exit 1
+        is_network_manager_active || exit_execution 1
     ;;
     "is_network_manager_enabled")
-        is_network_manager_enabled || exit 1
+        is_network_manager_enabled || exit_execution 1
     ;;
     "test_network_manager")
         test_network_manager
@@ -518,10 +526,10 @@ case "${ACTION}" in
         get_network_exist_flag
     ;;
     "is_wifi_power_safe_enabled")
-        is_wifi_power_safe_enabled || exit 1
+        is_wifi_power_safe_enabled || exit_execution 1
     ;;
     "set_wifi_power_safe")
-        set_wifi_power_safe "$1" || exit 1
+        set_wifi_power_safe "$1" || exit_execution 1 "$1"
     ;;
     *)
         do_help
@@ -530,5 +538,4 @@ case "${ACTION}" in
         exit 1
 esac
 
-#print_log $LOG_FILE "INFO" "##### Exit executing operation: $ACTION #####"
-exit 0
+exit_execution 0 "$1" "$2" "$3"
